#!/usr/bin/env python3
"""
MSM8996 Display Register Dictionary
Sony Xperia XZs (Keyaki / MSM8996 v3.0)

Defines register metadata across MDSS, DSI0 CTRL, DSI0 PHY, DSI0 PLL, and MMCC.
Used by compare_display_state.py and XNU state validation tools.
"""

from typing import Dict, Any, Optional

class AccessType:
    RO_SAFE = "RO_SAFE"
    RW_CONFIG = "RW_CONFIG"
    WO = "WO"
    CLEAR_ON_READ = "CLEAR_ON_READ"
    UNKNOWN = "UNKNOWN"

class SideEffect:
    SAFE = "SAFE"
    STATE_ALTERING = "STATE_ALTERING"
    FATAL_IF_TOUCHED = "FATAL_IF_TOUCHED"

class Subsystem:
    DSI_CTRL = "DSI_CTRL"
    DSI_PHY = "DSI_PHY"
    DSI_PLL = "DSI_PLL"
    MMCC = "MMCC"
    MDP = "MDP"

# Register Definition Schema:
# {
#   "name": str,
#   "subsystem": str,
#   "base": int,
#   "offset": int,
#   "address": int,
#   "mask": int,               # Default compare mask
#   "access": AccessType,
#   "side_effect": SideEffect,
#   "is_volatile": bool,        # If true, skipped during normal deterministic comparison
#   "description": str,
# }

DISPLAY_REGISTERS: Dict[int, Dict[str, Any]] = {
    # =========================================================================
    # DSI0 Controller Registers (Base = 0x00994000)
    # =========================================================================
    0x00994000: {
        "name": "DSI_HW_VERSION",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x000,
        "address": 0x00994000,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "DSI controller hardware revision (Expected: 0x10040001 = v1.4.1)",
    },
    0x0099400c: {
        "name": "DSI_CTRL_0",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x00c,
        "address": 0x0099400c,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI controller configuration 0",
    },
    0x00994010: {
        "name": "DSI_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x010,
        "address": 0x00994010,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI controller status flags",
    },
    0x00994014: {
        "name": "DSI_FIFO_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x014,
        "address": 0x00994014,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI FIFO fill status",
    },
    0x00994018: {
        "name": "DSI_TIMING_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x018,
        "address": 0x00994018,
        "mask": 0x0000003f,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI timing control (t_clk_post = 27)",
    },
    0x009940f0: {
        "name": "DSI_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0f0,
        "address": 0x009940f0,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI master enable (Bit 0 = 1: DSI Host Enabled)",
    },
    0x00994110: {
        "name": "DSI_COMMAND_MODE_MDP_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x110,
        "address": 0x00994110,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Command mode MDP interface control",
    },
    0x0099412c: {
        "name": "DSI_PHY_SW_RESET",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x12c,
        "address": 0x0099412c,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI PHY software reset assertion",
    },
    0x009941b4: {
        "name": "DSI_EOT_PACKET_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x1b4,
        "address": 0x009941b4,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "EoT packet generation and checking control",
    },
    0x009941b8: {
        "name": "DSI_LANE_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x1b8,
        "address": 0x009941b8,
        "mask": 0x00000007,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "DSI lane state status (0x6 = LP-11 idle)",
    },
    0x009941f4: {
        "name": "DSI_LANE_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x1f4,
        "address": 0x009941f4,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI lane enable (Expected: 0x03000104 = 4 Data Lanes + CLK)",
    },
    0x009942a0: {
        "name": "DSI_T_CLK_PRE_EXTEND",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x2a0,
        "address": 0x009942a0,
        "mask": 0x0000003f,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Clock preamble extension (t_clk_pre = 43)",
    },

    # =========================================================================
    # DSI0 14nm PHY Registers (Base = 0x00994400)
    # =========================================================================
    0x00994410: {
        "name": "PHY_CMN_CTRL_0",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x010,
        "address": 0x00994410,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PHY common control register 0",
    },
    0x00994440: {
        "name": "DL0_STRENGTH_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x040,
        "address": 0x00994440,
        "mask": 0x0000ffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 0 drive strength control",
    },
    0x00994448: {
        "name": "PHY_CMN_CLK_CFG0",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x048,
        "address": 0x00994448,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PHY clock config 0 (PLL enable kick)",
    },
    0x0099444c: {
        "name": "PHY_CMN_CLK_CFG1",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x04c,
        "address": 0x0099444c,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PHY clock config 1 (Post-N1 divider = 2)",
    },
    0x00994564: {
        "name": "DL0_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x164,
        "address": 0x00994564,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 0 internal LDO regulator bias (0x1d)",
    },
    0x009945e4: {
        "name": "DL1_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x1e4,
        "address": 0x009945e4,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 1 internal LDO regulator bias (0x1d)",
    },
    0x00994664: {
        "name": "DL2_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x264,
        "address": 0x00994664,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 2 internal LDO regulator bias (0x1d)",
    },
    0x009946e4: {
        "name": "DL3_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x2e4,
        "address": 0x009946e4,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 3 internal LDO regulator bias (0x1d)",
    },
    0x00994764: {
        "name": "CLK_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x364,
        "address": 0x00994764,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Clock lane internal LDO regulator bias (0x1d)",
    },

    # =========================================================================
    # DSI0 14nm PLL Registers (Base = 0x00994800)
    # =========================================================================
    0x00994800: {
        "name": "PLL_SYSCLK_EN_RESET",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x000,
        "address": 0x00994800,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PLL system clock enable and soft reset",
    },
    0x0099483c: {
        "name": "PLL_PLLLOCK_CMP1",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x03c,
        "address": 0x0099483c,
        "mask": 0x0000001f,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PLL lock comparison threshold byte 0 (0x57 / mask 0x1f)",
    },
    0x00994840: {
        "name": "PLL_PLLLOCK_CMP2",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x040,
        "address": 0x00994840,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PLL lock comparison threshold byte 1 (0x09)",
    },
    0x00994850: {
        "name": "PLL_RESETSM_READY_STATUS_UPSTREAM",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x050,
        "address": 0x00994850,
        "mask": 0x00000021,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "Upstream DRM PLL status: Bit 5 = LOCK, Bit 0 = READY",
    },
    0x0099485c: {
        "name": "PLL_CMN_CONFIG",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x05c,
        "address": 0x0099485c,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Common PLL output buffer enable (0x10)",
    },
    0x0099486c: {
        "name": "PLL_DEC_START",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x06c,
        "address": 0x0099486c,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Integer decimation start divider (0x5d = 93)",
    },
    0x00994870: {
        "name": "PLL_DIV_FRAC_START1",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x070,
        "address": 0x00994870,
        "mask": 0x00000003,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Fractional divider start part 1 (0xf0 / hardware mask 0x03)",
    },
    0x00994874: {
        "name": "PLL_DIV_FRAC_START2",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x074,
        "address": 0x00994874,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Fractional divider start part 2 (0x40)",
    },
    0x00994878: {
        "name": "PLL_DIV_FRAC_START3",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x078,
        "address": 0x00994878,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Fractional divider start part 3 (0x07)",
    },
    0x009948cc: {
        "name": "PLL_RESET_SM_STATUS_DOWNSTREAM",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x0cc,
        "address": 0x009948cc,
        "mask": 0x00000021,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "Downstream Qualcomm 3.18 status: Bit 5 = LOCK, Bit 0 = READY",
    },

    # =========================================================================
    # MMCC DSI Branch Registers (Base = 0x008c0000)
    # =========================================================================
    0x008c2000: {
        "name": "PCLK0_CMD_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2000,
        "address": 0x008c2000,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Pixel clock 0 command register (Bit 0 = UPDATE)",
    },
    0x008c2004: {
        "name": "PCLK0_CFG_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2004,
        "address": 0x008c2004,
        "mask": 0x00000700,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Pixel clock 0 config register (Source select = DSI0 PLL)",
    },
    0x008c2120: {
        "name": "BYTE0_CMD_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2120,
        "address": 0x008c2120,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Byte clock 0 command register (Bit 0 = UPDATE)",
    },
    0x008c2124: {
        "name": "BYTE0_CFG_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2124,
        "address": 0x008c2124,
        "mask": 0x00000700,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Byte clock 0 config register (Source select = DSI0 PLL)",
    },
    0x008c2160: {
        "name": "ESC0_CMD_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2160,
        "address": 0x008c2160,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Escape clock 0 command register (Bit 0 = UPDATE)",
    },
    0x008c2164: {
        "name": "ESC0_CFG_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2164,
        "address": 0x008c2164,
        "mask": 0x00000700,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Escape clock 0 config register (Source select = XO)",
    },
    0x008c2314: {
        "name": "PCLK0_CBCR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2314,
        "address": 0x008c2314,
        "mask": 0x80000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Pixel clock 0 branch control (Bit 0 = Enable, Bit 31 = Halt)",
    },
    0x008c233c: {
        "name": "BYTE0_CBCR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x233c,
        "address": 0x008c233c,
        "mask": 0x80000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Byte clock 0 branch control (Bit 0 = Enable, Bit 31 = Halt)",
    },
    0x008c2344: {
        "name": "ESC0_CBCR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2344,
        "address": 0x008c2344,
        "mask": 0x80000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Escape clock 0 branch control (Bit 0 = Enable, Bit 31 = Halt)",
    },
}

def get_register(addr: int) -> Optional[Dict[str, Any]]:
    """Look up register metadata by physical address."""
    return DISPLAY_REGISTERS.get(addr)

def get_registers_by_subsystem(subsystem: str) -> Dict[int, Dict[str, Any]]:
    """Return all registers belonging to a subsystem."""
    return {addr: meta for addr, meta in DISPLAY_REGISTERS.items() if meta["subsystem"] == subsystem}
