#!/usr/bin/env python3
"""
MSM8996 Display Register Dictionary
Sony Xperia XZs (Keyaki / MSM8996 v3.0)

Defines register metadata across MDSS, DSI0 CTRL, DSI0 PHY, DSI0 PLL, and MMCC.
Used by compare_display_state.py and XNU state validation tools.
"""

from typing import Dict, Any, Optional

class AccessType:
    RO_SAFE = "RO_SAFE"
    RW_CONFIG = "RW_CONFIG"
    WO = "WO"
    CLEAR_ON_READ = "CLEAR_ON_READ"
    UNKNOWN = "UNKNOWN"

class SideEffect:
    SAFE = "SAFE"
    STATE_ALTERING = "STATE_ALTERING"
    FATAL_IF_TOUCHED = "FATAL_IF_TOUCHED"

class Subsystem:
    DSI_CTRL = "DSI_CTRL"
    DSI_PHY = "DSI_PHY"
    DSI_PLL = "DSI_PLL"
    MMCC = "MMCC"
    MDP = "MDP"

# Register Definition Schema:
# {
#   "name": str,
#   "subsystem": str,
#   "base": int,
#   "offset": int,
#   "address": int,
#   "mask": int,               # Default compare mask
#   "access": AccessType,
#   "side_effect": SideEffect,
#   "is_volatile": bool,        # If true, skipped during normal deterministic comparison
#   "description": str,
# }

DISPLAY_REGISTERS: Dict[int, Dict[str, Any]] = {
    # =========================================================================
    # DSI0 Controller Registers (Base = 0x00994000)
    # Source-derived from Qualcomm MSM8996 downstream mdss_dsi_host.c
    # =========================================================================
    0x00994000: {
        "name": "DSI_HW_VERSION",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x000,
        "address": 0x00994000,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "DSI controller hardware revision (Expected: 0x10040001 = v1.4.1)",
    },
    0x00994004: {
        "name": "DSI_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x004,
        "address": 0x00994004,
        "mask": 0x000001ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI master control (Expected: 0x1f5 for Keyaki: ctrl_en|cmd_en|DL0-3|clk_en)",
    },
    0x00994008: {
        "name": "DSI_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x008,
        "address": 0x00994008,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI controller status flags (Bit 4 = BTA_BUSY)",
    },
    0x0099400c: {
        "name": "DSI_FIFO_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x00c,
        "address": 0x0099400c,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI FIFO status (bits [31:12] empty indicators, e.g. 0x11111000)",
    },
    0x0099403c: {
        "name": "DSI_COMMAND_MODE_DMA_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x03c,
        "address": 0x0099403c,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Command mode DMA control",
    },
    0x00994040: {
        "name": "DSI_COMMAND_MODE_MDP_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x040,
        "address": 0x00994040,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Command mode MDP interface control, stream packing",
    },
    0x00994044: {
        "name": "DSI_COMMAND_MODE_MDP_DCS_CMD_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x044,
        "address": 0x00994044,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Command mode MDP DCS command control (wr_mem_start=0x2c, wr_mem_continue=0x3c)",
    },
    0x00994048: {
        "name": "DSI_DMA_CMD_OFFSET",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x048,
        "address": 0x00994048,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DMA command buffer physical base address",
    },
    0x0099404c: {
        "name": "DSI_DMA_CMD_LENGTH",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x04c,
        "address": 0x0099404c,
        "mask": 0x00ffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DMA command buffer byte length",
    },
    0x00994050: {
        "name": "DSI_DMA_FIFO_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x050,
        "address": 0x00994050,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DMA FIFO watermark control",
    },
    0x00994054: {
        "name": "DSI_DMA_NULL_PACKET_DATA",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x054,
        "address": 0x00994054,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DMA NULL packet data register",
    },
    0x00994058: {
        "name": "DSI_COMMAND_MODE_MDP_STREAM0_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x058,
        "address": 0x00994058,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Command mode MDP stream 0 format control",
    },
    0x0099405c: {
        "name": "DSI_COMMAND_MODE_MDP_STREAM0_TOTAL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x05c,
        "address": 0x0099405c,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Command mode MDP stream 0 total pixels",
    },
    0x00994068: {
        "name": "DSI_ACK_ERR_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x068,
        "address": 0x00994068,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI acknowledge error status",
    },
    0x0099406c: {
        "name": "DSI_RDBK_DATA0",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x06c,
        "address": 0x0099406c,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "Readback FIFO data register 0",
    },
    0x00994084: {
        "name": "DSI_TRIG_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x084,
        "address": 0x00994084,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Trigger source multiplexer control",
    },
    0x00994090: {
        "name": "DSI_CMD_MODE_DMA_SW_TRIGGER",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x090,
        "address": 0x00994090,
        "mask": 0x00000001,
        "access": AccessType.WO,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Self-clearing write 1 triggers DMA command transmission",
    },
    0x00994094: {
        "name": "DSI_CMD_MODE_MDP_SW_TRIGGER",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x094,
        "address": 0x00994094,
        "mask": 0x00000001,
        "access": AccessType.WO,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Self-clearing write 1 triggers MDP stream transmission",
    },
    0x00994098: {
        "name": "DSI_CMD_MODE_BTA_SW_TRIGGER",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x098,
        "address": 0x00994098,
        "mask": 0x00000001,
        "access": AccessType.WO,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Self-clearing write 1 triggers Bus Turnaround",
    },
    0x0099409c: {
        "name": "DSI_RESET_SW_TRIGGER",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x09c,
        "address": 0x0099409c,
        "mask": 0x00000001,
        "access": AccessType.WO,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Software reset trigger",
    },
    0x009940a8: {
        "name": "DSI_LANE_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0a8,
        "address": 0x009940a8,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI lane stopstate status",
    },
    0x009940ac: {
        "name": "DSI_LANE_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0ac,
        "address": 0x009940ac,
        "mask": 0x0000001f,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI lane control (ULPS request for clock and data lanes 0-3)",
    },
    0x009940b0: {
        "name": "DSI_LANE_SWAP_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0b0,
        "address": 0x009940b0,
        "mask": 0x00000007,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane permutation / mapping control",
    },
    0x009940b8: {
        "name": "DSI_LP_TIMER_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0b8,
        "address": 0x009940b8,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Low-power timer control",
    },
    0x009940bc: {
        "name": "DSI_HS_TIMER_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0bc,
        "address": 0x009940bc,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "High-speed timer control",
    },
    0x009940c0: {
        "name": "DSI_TIMEOUT_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0c0,
        "address": 0x009940c0,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "DSI timeout status flags",
    },
    0x009940c4: {
        "name": "DSI_CLKOUT_TIMING_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0c4,
        "address": 0x009940c4,
        "mask": 0x00003f3f,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Timing control: [13:8] = t_clk_post (0x1b), [5:0] = t_clk_pre (0x2b), Expected: 0x00001b2b",
    },
    0x009940cc: {
        "name": "DSI_EOT_PACKET_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x0cc,
        "address": 0x009940cc,
        "mask": 0x00000011,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "EoT packet generation and checking control (Bit 0 = TX_EOT, Bit 4 = RX_EOT_IGNORE)",
    },
    0x0099410c: {
        "name": "DSI_ERR_INT_MASK0",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x10c,
        "address": 0x0099410c,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Error interrupt mask (Expected: 0x0003fd08)",
    },
    0x00994110: {
        "name": "DSI_INT_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x110,
        "address": 0x00994110,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI host interrupt control & mask",
    },
    0x00994118: {
        "name": "DSI_SOFT_RESET",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x118,
        "address": 0x00994118,
        "mask": 0x00000001,
        "access": AccessType.WO,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Core software reset (pulse 1 then 0)",
    },
    0x0099411c: {
        "name": "DSI_CLK_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x11c,
        "address": 0x0099411c,
        "mask": 0x000003ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Clock gating and distribution control (Expected: 0x23f)",
    },
    0x00994120: {
        "name": "DSI_CLK_STATUS",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x120,
        "address": 0x00994120,
        "mask": 0xffffffff,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": True,
        "description": "Clock status register",
    },
    0x009942a0: {
        "name": "DSI_VIDEO_COMPRESSION_MODE_CTRL",
        "subsystem": Subsystem.DSI_CTRL,
        "base": 0x00994000,
        "offset": 0x2a0,
        "address": 0x009942a0,
        "mask": 0xffffffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "DSI video compression mode control (DSC - unused on Keyaki uncompressed panel)",
    },

    # =========================================================================
    # DSI0 14nm PHY Registers (Base = 0x00994400)
    # =========================================================================
    0x00994410: {
        "name": "PHY_CMN_CTRL_0",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x010,
        "address": 0x00994410,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PHY common control register 0",
    },
    0x00994440: {
        "name": "DL0_STRENGTH_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x040,
        "address": 0x00994440,
        "mask": 0x0000ffff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 0 drive strength control",
    },
    0x00994448: {
        "name": "PHY_CMN_CLK_CFG0",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x048,
        "address": 0x00994448,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PHY clock config 0 (PLL enable kick)",
    },
    0x0099444c: {
        "name": "PHY_CMN_CLK_CFG1",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x04c,
        "address": 0x0099444c,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PHY clock config 1 (Post-N1 divider = 2)",
    },
    0x00994564: {
        "name": "DL0_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x164,
        "address": 0x00994564,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 0 internal LDO regulator bias (0x1d)",
    },
    0x009945e4: {
        "name": "DL1_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x1e4,
        "address": 0x009945e4,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 1 internal LDO regulator bias (0x1d)",
    },
    0x00994664: {
        "name": "DL2_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x264,
        "address": 0x00994664,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 2 internal LDO regulator bias (0x1d)",
    },
    0x009946e4: {
        "name": "DL3_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x2e4,
        "address": 0x009946e4,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Data lane 3 internal LDO regulator bias (0x1d)",
    },
    0x00994764: {
        "name": "CLK_REGULATOR_CTRL",
        "subsystem": Subsystem.DSI_PHY,
        "base": 0x00994400,
        "offset": 0x364,
        "address": 0x00994764,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Clock lane internal LDO regulator bias (0x1d)",
    },

    # =========================================================================
    # DSI0 14nm PLL Registers (Base = 0x00994800)
    # =========================================================================
    0x00994800: {
        "name": "PLL_SYSCLK_EN_RESET",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x000,
        "address": 0x00994800,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "PLL system clock enable and soft reset",
    },
    0x0099483c: {
        "name": "PLL_PLLLOCK_CMP1",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x03c,
        "address": 0x0099483c,
        "mask": 0x0000001f,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Kvco divider ref 2 / lock cmp low byte (0x05)",
    },
    0x00994840: {
        "name": "PLL_PLLLOCK_CMP2",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x040,
        "address": 0x00994840,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Kvco divider ref 1 / lock cmp high byte (0x5f)",
    },
    0x00994850: {
        "name": "PLL_RESETSM_READY_STATUS_UPSTREAM",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x050,
        "address": 0x00994850,
        "mask": 0x00000021,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "Upstream DRM PLL status: Bit 5 = LOCK, Bit 0 = READY",
    },
    0x0099485c: {
        "name": "PLL_CMN_CONFIG",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x05c,
        "address": 0x0099485c,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Common PLL output buffer enable (0x10)",
    },
    0x0099486c: {
        "name": "PLL_DEC_START",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x06c,
        "address": 0x0099486c,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "VCO divider ref 1 (0x5f)",
    },
    0x00994870: {
        "name": "PLL_DIV_FRAC_START1",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x070,
        "address": 0x00994870,
        "mask": 0x00000003,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "VCO divider ref 2 (0x00)",
    },
    0x00994874: {
        "name": "PLL_DIV_FRAC_START2",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x074,
        "address": 0x00994874,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "VCO count 1 (0x81)",
    },
    0x00994878: {
        "name": "PLL_DIV_FRAC_START3",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x078,
        "address": 0x00994878,
        "mask": 0x000000ff,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "VCO count 2 (0x03)",
    },
    0x009948cc: {
        "name": "PLL_RESET_SM_STATUS_DOWNSTREAM",
        "subsystem": Subsystem.DSI_PLL,
        "base": 0x00994800,
        "offset": 0x0cc,
        "address": 0x009948cc,
        "mask": 0x00000021,
        "access": AccessType.RO_SAFE,
        "side_effect": SideEffect.SAFE,
        "is_volatile": False,
        "description": "Downstream Qualcomm 3.18 status: Bit 5 = LOCK, Bit 0 = READY",
    },

    # =========================================================================
    # MMCC DSI Branch Registers (Base = 0x008c0000)
    # =========================================================================
    0x008c2000: {
        "name": "PCLK0_CMD_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2000,
        "address": 0x008c2000,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Pixel clock 0 command register (Bit 0 = UPDATE)",
    },
    0x008c2004: {
        "name": "PCLK0_CFG_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2004,
        "address": 0x008c2004,
        "mask": 0x00000700,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Pixel clock 0 config register (Source select = DSI0 PLL)",
    },
    0x008c2120: {
        "name": "BYTE0_CMD_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2120,
        "address": 0x008c2120,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Byte clock 0 command register (Bit 0 = UPDATE)",
    },
    0x008c2124: {
        "name": "BYTE0_CFG_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2124,
        "address": 0x008c2124,
        "mask": 0x00000700,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Byte clock 0 config register (Source select = DSI0 PLL)",
    },
    0x008c2160: {
        "name": "ESC0_CMD_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2160,
        "address": 0x008c2160,
        "mask": 0x00000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": True,
        "description": "Escape clock 0 command register (Bit 0 = UPDATE)",
    },
    0x008c2164: {
        "name": "ESC0_CFG_RCGR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2164,
        "address": 0x008c2164,
        "mask": 0x00000700,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Escape clock 0 config register (Source select = XO)",
    },
    0x008c2314: {
        "name": "PCLK0_CBCR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2314,
        "address": 0x008c2314,
        "mask": 0x80000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Pixel clock 0 branch control (Bit 0 = Enable, Bit 31 = Halt)",
    },
    0x008c233c: {
        "name": "BYTE0_CBCR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x233c,
        "address": 0x008c233c,
        "mask": 0x80000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Byte clock 0 branch control (Bit 0 = Enable, Bit 31 = Halt)",
    },
    0x008c2344: {
        "name": "ESC0_CBCR",
        "subsystem": Subsystem.MMCC,
        "base": 0x008c0000,
        "offset": 0x2344,
        "address": 0x008c2344,
        "mask": 0x80000001,
        "access": AccessType.RW_CONFIG,
        "side_effect": SideEffect.STATE_ALTERING,
        "is_volatile": False,
        "description": "Escape clock 0 branch control (Bit 0 = Enable, Bit 31 = Halt)",
    },
}

def get_register(addr: int) -> Optional[Dict[str, Any]]:
    """Look up register metadata by physical address."""
    return DISPLAY_REGISTERS.get(addr)

def get_registers_by_subsystem(subsystem: str) -> Dict[int, Dict[str, Any]]:
    """Return all registers belonging to a subsystem."""
    return {addr: meta for addr, meta in DISPLAY_REGISTERS.items() if meta["subsystem"] == subsystem}
